spring:
  application:
    name: spring-pekko

server:
  port: 8080

pekko:
  name: spring-pekko-example
  actor:
    provider: cluster
    allow-java-serialization: on
    warn-about-java-serializer-usage: off
  remote:
    artery:
      canonical:
        hostname: 127.0.0.1
        port: 2551
  cluster:
    name: spring-pekko-example-cluster
    seed-nodes:
      - pekko://spring-pekko-example-cluster@127.0.0.1:2551
      - pekko://spring-pekko-example-cluster@127.0.0.1:2552
      - pekko://spring-pekko-example-cluster@127.0.0.1:2553
    downing-provider-class: org.apache.pekko.cluster.sbr.SplitBrainResolverProvider
