spring:
  application:
    name: spring-pekko

pekko:
  actor:
    provider: cluster
    allow-java-serialization: on
    warn-about-java-serializer-usage: off
  remote:
    artery:
      canonical:
        hostname: 127.0.0.1
        port: 2551
  cluster:
    name: cluster-actor-system
    seed-nodes:
      - pekko://clusterName@127.0.0.1:2551
      - pekko://clusterName@127.0.0.1:2552
      - pekko://clusterName@127.0.0.1:2553
    downing-provider-class: org.apache.pekko.cluster.sbr.SplitBrainResolverProvider
